### PR TITLE
Add profile for hybrid inverters from CHINT

### PR DESCRIPTION
**Pull request by gardiol**
Should work for most CHINT inverters connected to Solarman

### CODE REVIEW

**Comment by gardiol** [comment]
The PDF is for any CHINT inverters, as far as the support told me.

**Comment by gardiol** [comment]
If you want to also update the documentation, i have the CPS SCE4.6~6KTL-120/EU model (https://en.chintpower.com/service/index/cid/10000/keywords/SCE.html)

**Comment by davidrapan** [comment]
Hi @gardiol, thanks for your PR.

The file should follow general structure of already present profiles.

* File name should start with the brand name followed by model type without specific rated power (e.g. 4.6~6K)
* Entity names in the file have to follow our naming scheme, some examples:
  * `Load L1 Power/Voltage/Current`
  * `Load Power` for sum of all phases
  * `Battery` for battery level
  * `Output L1 Power/Voltage/Current`
  * `Power` for sum of all output phases
  * etc., you can find all the examples which follow this standard in deye_sg04lp3.yaml profile

**Comment by gardiol** [comment]
Ok, will work on that tomorrow....

**Comment by gardiol** [comment]
Hi! i need some support, if you can, understanding all the fields in the PDF i have attached, because i probably lack some knowledge about PV and such.

I am trying to match some stuff between the deye you suggested and the CHINT documentation.

- The "Phase X Voltage/Current/Power" exposed by the CHINT (see PDF page 5, index 1-12) what would be mapped to according to the deye names?
- The various "PVX Voltage/Current" and "MPPTX Power" exposed by the CHINT (see PDF page 5, index 13-21 and 34-53) what whould be mapped to according to the deye names?

Might be a stupid question, but i think the CHINT document is really a bad translation of an already messy original... and my ignorance doesn't help.

**Comment by davidrapan** [comment]
1) Those are probably inverters own output values
  Inverter should have three set of phases parameters (Power - always present, Current - often present, Voltage - is mostly left out): Output, Load, Grid (Sometime there are multiple CT on this line which are called External LX on the far side and Internal LX on the closer side from inverters POV)
2) PVX Voltage/Current are correct and MPPTX Power should be named in similar manner thus PVX Power

Hope it's clear enough and if you have any more questions don't hesitate to ask! 😉

**Comment by gardiol** [comment]
I think i have mapped most of the inputs, but i am left with the followings:
```
      - name: "Total Load Consumption"
        class: "energy"
        state_class: "total_increasing"
        uom: "kWh"
        scale: 0.1
        rule: 3
        registers: [0x020F, 0x0210]
        validation:
          min: 0.1
```

Any insights on how they sohuld be mapped? If they don't have equivalent mappings, i will just map them with a meaningful name (any help appreciated)...

a few leftovers to add, and i should be set.

**Comment by gardiol** [comment]
I also have another question. It seems that any 32bit  (2 registers) values i need to read inverting the registers ex: [0x1027, 0x1028] must be written as [0x1028, 0x1027] for the value to be correct.

While i can manually swap them all, this is not the case in the deye example nor i can find a way to configure values with this inverted endianess so that i do not need to swap them all manually?

In the CHINT pdf i cannot find anything about endianess, so i assume it's something "untold" or just unexpected?

**Comment by davidrapan** [comment]
* `Reactive Power` has class: "reactive_power", uom: "var" and name is okay
* `Active Power` has class: "power", uom: "W" and this is probably sum of all inverter outputs so should be called just `Power`
* `Power Factor` has class: "power_factor", uom: "%" and name is okay

Not sure what values `Accumulated energy of positive` and `Accumulated energy of negative` are displaying, can you show me?

> I also have another question. It seems that any 32bit (2 registers) values i need to read inverting the registers ex: [0x1027, 0x1028] must be written as [0x1028, 0x1027] for the value to be correct.

The order is always low and high 16b.

> While i can manually swap them all, this is not the case in the deye example nor i can find a way to configure values with this inverted endianness so that i do not need to swap them all manually?

Yeah not every inverter has the registers in order.

**Comment by gardiol** [comment]
> Not sure what values `Accumulated energy of positive` and `Accumulated energy of negative` are displaying, can you show me? (In comparison to other values)

They show a good solid +10Wh constant over time, since the last 6 hours at least they don't change a bit

**Comment by davidrapan** [comment]
I have honestly no idea what those values means... guess you can left them as they are.

Btw `Battery` entities shows zeroes, is that correct?

Also the deye_sg04lp3 have `Battery *` entities as well `Battery BMS *` because the device also exposes some raw BMS data. In your case you can proly just get rid of the `BMS` there. Also sensor which only shows the battery level should be called just `Battery`.

**Comment by gardiol** [comment]
I do not have batteries... i think that's why it shows 0. Which of the parameters should be named battery? Maybe "Battery  SOC", ,which is expressed as a %?

As for BMS, i am not sure, it seems there is not much about BMS in the CHINT PDF, so i will just rename those info as battery and not BMS, as they appear in the PDF.

A few more questions.

One about this entity: 
`Decimals of total energy | 0x104C | 1 | U16 | Relate to 0x1021, if total energy is 220.836kwh, then 0x104C is 836wh | RO | Wh`

They are the "less than 1kWh" part of the total energy. Is it important to add them to the total energy? If so, how should i do it? i  mean, what do i need to write in the YAML.

The last question is on the various "writable" entities i have in the PDF, which are quite a lot, should i implement them? I am wary to mess with those, so...

**Comment by davidrapan** [comment]
> I do not have batteries... i think that's why it shows 0. Which of the parameters should be named battery? Maybe "Battery SOC", ,which is expressed as a %?

Yes.

> As for BMS, i am not sure, it seems there is not much about BMS in the CHINT PDF, so i will just rename those info as battery and not BMS, as they appear in the PDF.

Yes, just leave out the BMS part.

> One about this entity:
Decimals of total energy | 0x104C | 1 | U16 | Relate to 0x1021, if total energy is 220.836kwh, then 0x104C is 836wh | RO | Wh
They are the "less than 1kWh" part of the total energy. Is it important to add them to the total energy? If so, how should i do it? i mean, what do i need to write in the YAML.

Pfuuuu, they are ridiculous! Is really the Total Energy without less than 1kWh part? If so it is doable using our custom sensors. It would be something like this:
```
      - name: "Total Production"
        class: "energy"
        state_class: "total_increasing"
        uom: "Wh"
        rule: 3
        registers: [0x1021, 0x104C]
        icon: "mdi:solar-power"
        sensors:
          - registers: [0x1021]
          - registers: [0x104C]
        validation:
          min: 0.1
```

> The last question is on the various "writable" entities i have in the PDF, which are quite a lot, should i implement them? I am wary to mess with those, so...

It's totally up to you, you really don't need to. Some profiles do contain some of those but implementing them should also mean you try them if it works and if you are not comfortable with that it's totally fine. 😉

**Comment by davidrapan** [comment]
Edit: fixed scaling in the provided example of custom sensor 😉

**Comment by davidrapan** [comment]
> Interesting enough, the "decimals" seems to be always zero... will investigate a bit more, beside that, things should be almost ready.

You can still define the sensor as in the example above. There is proly nothing wrong with that. But I'm not really surprised.

> Is it normal that reactive power is always negative? like between -2000 and -6000 var? It fluctuates... but not sure if correct.

Positive numbers are for inductive loads (e.g. motors) and negative numbers are for capacitive loads (e,g pc).

> The values that i can double check with the Solarman app, do match.

👍

**Comment by gardiol** [comment]
Ok, i have updated my repo, the PR should be updated as well. 

Check it out, see if there are more changes needed or things to improve. I have left all three total productions: fixed, decimals, and "combined" with the last one as being the correct named one.

**Comment by davidrapan** [comment]
Great. One more thing what about to combine all the static info into single sensor entity called `Device` using attributes? It's really required but does clear out from the list values which are not changing with time.

It's done using attribute: over entity which you want turn into attribute. And then with attributes: ["Name of entity", "Name of other entity", ...]. Can be seen in the sg04lp3 profile.

**Comment by davidrapan** [comment]
You are maybe missing Today Energy Import/Export?

**Comment by davidrapan** [comment]
Power losses custom sensor:
```
      - name: "Power losses"
        description: Includes consumption of the inverter device itself as well AC/DC conversion losses
        class: "power"
        state_class: "measurement"
        uom: "W"
        scale: 0.1
        rule: 1
        registers: [0x1049, 0x1048, 0x200A, 0x2009, 0x1038, 0x1037]
        uint: enforce
        sensors:
          - registers: [0x1049, 0x1048]
          - registers: [0x200A, 0x2009]
          - operator: subtract
            signed:
            registers: [0x1038, 0x1037]
```

**Comment by davidrapan** [comment]
Okay I know what those `Accumulated energy of positive` and `Accumulated energy of negative` are. They are `Total Energy Import/Export`.

Those you have currently named `Total Energy Import/Export` are `Today Energy Import/Export`.

**Comment by gardiol** [comment]
Make sense.. .you think  .. of positive = exported to the grid and .. of negative = imported from the grid?
OR vide-versa?

**Comment by gardiol** [comment]
Screenshot_20241010_204751

Do you make sens out of this? I have labeled "total energy import" from "of positive" and "total energy export" from "of negative", but still doesnt make too much sense to me considering the today energy import/export. My PV is operative since march 2024.

**Comment by davidrapan** [comment]
Not sure about the truthfulness of the values but they for sure makes more sense in respect to each other.

**Comment by davidrapan** [comment]
And you forgot the `Total Load Consumption`. Looks like it still shows the `Today Load Consumption` value.

**Comment by davidrapan** [comment]
And screenshots from before were showing very low values for them to be a totals. So I'm like 99% sure this is the correct interpretation of the documentation provided.

**Comment by gardiol** [comment]
Looking from the solarman app, I cannot match the totals export/imports.

Solarman app says 2.96mW of consumption, which I don't find anywhere in the data above... And 2.14mWh of purchased power, again cannot find it anywhere above.

Total energy export instead is perfectly fit the amount shown by solarman app.

Sorry for Italian in screenshot:
Screenshot_20241010-211259_SOLARMAN Smart

**Comment by gardiol** [comment]
I also have the "load energy" entity that I cannot match with anything from solarman app...

**Comment by davidrapan** [comment]
That means even your original interpretation was incorrect. Your original totals were very low thus indication they are today's values indeed but yeah the only one which does match is Energy Export: 742kWh. But in the end those are the only values we got so...

**Comment by davidrapan** [comment]
You know the truth is that the registers are just incremental indicators of accrued values and CAN reset to 0 and indicate new cycle. Data collector e.g Solarman App or HA is the one who than creates statistics over raw data from inverter.

**In other words it's in fact completely normal that those values are lower then in Solarman App.**

**Comment by davidrapan** [comment]
I can show you later on how to bring values in HA up to be in sync with those in Solarman App.

**Comment by davidrapan** [comment]
"Load Energy" # aka "Accumulated energy of load" is in fact `Total Load Consumption`.

**Comment by gardiol** [comment]
> "Load Energy" # aka "Accumulated energy of load" is in fact `Total Load Consumption`.

You mean today's load consumption? Because 14kWh doesn't seem to be a total but seems to match pretty close what solarman app shows as today's consumption...

**Comment by davidrapan** [comment]
Your currently named Total Load Consumption shows 13140Wh which is 13.14kWh. That is I suppose your Today Load Consumption.

Take the units into account!

**Comment by davidrapan** [comment]
Give me screenshot with your "Load Energy".

**Comment by gardiol** [comment]
Wait,  I think I got it now... Load energy is 1.5mWh, so a total, while the other one is 13kWh, so a daily one. 

What a mess, I am getting pretty confused. Probably better to do it tomorrow after a night sleep...

**Comment by davidrapan** [comment]
> Wait, I think I got it now... Load energy is 1.5mWh, so a total, while the other one is 13kWh, so a daily one.

Exactly! 👍

**Comment by davidrapan** [comment]
What are total sensors really used for is their delta from previous recorded value, not their current value. And in same way is also using them Solarman App. That means that if for example you sometime during the usage let's say total reset of your device, thus zeroing all the values not HA or even Solarman App cares.

That's why it does not mean enything that the values now don't match. 😉

I really hope I explained it clearly.

**Comment by gardiol** [comment]
Ok, i think i have done what you suggested.
I have fixed the today/total mismatch, did a general review of the entire YAML (there where still couple of errors like 32bit entities with only one register), merged the "info" into one device with attributes, and added the two custom sensors.

About the custom sensors: they seem to be always "Unknown", is it due to having "Unknown" values for the battery data? Is there a way to have it calculate anyway?

The latest YAML is pushed to my repo, the PR should update accordingly.

**Comment by davidrapan** [comment]
Which version of the integration are you running currently? There were some updates recently regarding custom sensors spanning multiple separate modbus responses.

**Comment by gardiol** [comment]
24.10.04, i see no updates on my HA notifications?

**Comment by davidrapan** [comment]
One more - Today Losses:
```
      - name: Today Losses
        alt: Daily Losses
        friendly_name: Today's Losses
        description: Includes today's consumption of the inverter device itself as well AC/DC conversion losses
        class: "energy"
        state_class: "total_increasing"
        ensure_increasing:
        uom: "kWh"
        rule: 1
        scale: 0.01
        digits: 1
        registers: [0x1333, 0x1332, 0x1028, 0x1027, 0x2010, 0x200F, 0x1335, 0x1334, 0x1337, 0x1336, 0x200C, 0x200B]
        uint: enforce
        sensors:
          - registers: [0x1333, 0x1332]
          - registers: [0x1028, 0x1027]
            scale: 0.001
          - registers: [0x2010, 0x200F]
          - operator: subtract
            registers: [0x1335, 0x1334]
          - operator: subtract
            registers: [0x1337, 0x1336]
          - operator: subtract
            registers: [0x200C, 0x200B]
```

**Btw what's that eps stands for?**

**Comment by gardiol** [comment]
I assumed EPS stands for Emergency Power Supply, some kind of UPS system?
There is no indication at all in the docs of what that would be, and they are all zero's anyway, i assume dbecause i have no batteries installed

**Comment by gardiol** [comment]
After the update, "total losses" is still "unknown", while "today's losses" get's calculated. "power losses" changed from "unknown" to "0W"

**Comment by davidrapan** [comment]
Even EPS L1 Voltage is 0?

**Comment by gardiol** [comment]
Screenshot_20241011_151516

**Comment by davidrapan** [comment]
Hm weird, guess it's not really that important and it can be changed later on when you or someone else find out what's it really for. But according to the original name `EPS Stored Energy` should be `EPS Total Energy`? Cause it's also called by `Accumulated *` as other total registers.

**One last thing I think, don't you want to change the native unit of measurement for total sensors change rather to kWh instead of Wh?**

**Comment by davidrapan** [comment]
If so you have to change uom from Wh to kWh and scale from 10 to 0.01.

**Comment by gardiol** [comment]
Yes, we need somebody who has EPS and can confirm data. But i can indeed change accordingly to EPS Total Energy ,make sense. As for the unit of measure of the total sensors, yes, why not, but how? Isn't the UOM reported by the device itself?

**Comment by davidrapan** [comment]
Yes you just have to change alongside `uom` also change the `scale` accordingly... means 10 / 1000 = 0.01

**Comment by gardiol** [comment]
Like this?:
```
    - name: "Total Energy Import" # aka "Accumulated energy of positive"
      alt: "Total Energy Bought"
      description: "Total energy imported from the grid"
      class: "energy"
      state_class: "total_increasing"
      uom: "kWh" # was "Wh"
      scale: 0.01 # was "10"
      digits: 2 # added
      rule: 3
      registers: [0x1307, 0x1306]
      icon: "mdi:transmission-tower-import"
```

I did this, but i still see 1,300,000.00 Wh in the entity value? The ".00" has been added, so the change must have been recognized tough.

**Comment by davidrapan** [comment]
I would say that i remembers that Wh was set originally. Either switch it in the entity settings in HA or just remove and re-add whole device back.

**Comment by gardiol** [comment]
Committed all the new changes. 

One last qestion, i was noticing that some EPS and Battery values where 0xFFFFFFFFFA as "invalid", so i fixed that with:
```
      validation:
        min: 0
        max: 0xFFFFFFF9
```

Is this the correct approach? 

Anyway, everything seems to work just fine. Of course EPS and battery are not tested, and write values are not added, as we talked before. I could work on those later on maybe, if i feel confident enough.

**Comment by davidrapan** [comment]
Yeah I think that's alright. 😉

Show me screenshot of all the Today and Total values as a final check.

**Comment by gardiol** [comment]
Screenshot_20241011_161741

Screenshot_20241011_161818

Screenshot_20241011_161856

I didnt sshotted every entity, but the main ones i think are here

**Comment by davidrapan** [comment]
It looks okay I think. Just the Total Losses are not calculated proly cause of missing Total Battery Charge/Discharge. I'll try to come up with something to mitigate this.

**Comment by davidrapan** [comment]
I'm gonna change the filename before next release to chint_cps-sce-tl.yaml, so you know and are not surprised later. 😉

**Comment by davidrapan** [comment]
With [feat: Add per value validation for custom sensors](https://github.com/davidrapan/ha-solarman/commit/43c9e144c606a6df78158edf6b9f63745e34f773) you should be able to also add validation to custom sensors.

**It's intended to validate that Total Battery Charge/Discharge in Total Losses calculation.**

_I will add it into the profile later you don't have to PR it yourself._ 😉

**Comment by davidrapan** [comment]
@gardiol will you have to chance to try and confirm that Total Losses are working in the latest version of the code in the repo?

**I would like to release new version if test is successful.**

**Comment by gardiol** [comment]
Would love to, but how to install it?

**Comment by davidrapan** [comment]
Easiest for you will be for you to just replace content of `parser.py` and the profile.

**Comment by gardiol** [comment]
just updated by replacing parser & profile, and seems that total losses are still "unknown", will wait a bit more and in case edit this comment if it works, but it seems, it doesnt.

EPS Total Energy is not validated anymore, it was before, so i now get 4,294,967,290.00 Wh

Total Losses is the only "Unknown" value, everything else works.

**Comment by davidrapan** [comment]
Could you please enable debug logging and attach the file?

**Comment by gardiol** [comment]
[home-assistant_solarman_2024-10-12T17-19-01.010Z.zip](https://github.com/user-attachments/files/17350846/home-assistant_solarman_2024-10-12T17-19-01.010Z.zip)

Hope this log is enough

**Comment by davidrapan** [comment]
Mhhh it does not show any errors...

How familiar are you with the python? Do you think you would be able to debug `_read_registers_custom` in `parser.py` method by using `_LOGGER.debug()` and find where exactly it fails for Total Losses sensor? Or you will need an assistance with that?

Could you also test if `EPS Total energy` was broken by raising the validation to 0.01 by changing it back to 0?

**Comment by gardiol** [comment]
Yes van debug in mython, but probably not.before tomorrow evening or Monday.... Will do and report back

**Comment by davidrapan** [comment]
Sure, no problem!

**Comment by gardiol** [comment]
For EPs total, the "wrong" value is 0xFFFFFFFA probably that's why you are not masking it properly

**Comment by davidrapan** [comment]
There is max: 0xFFFFFFF9 which is lower than 0xFFFFFFFA, so..

**Comment by davidrapan** [comment]
I added debug logging to the validation in [refactor: Value validation for easier debugging](https://github.com/davidrapan/ha-solarman/commit/0669175874faae29953b8f971ee47e39fe9310f8)

You can maybe slightly alter it and place those `_LOGGER.debug()` outside of the if statement to always log in debug when the flow gets inside the function so we can see what's happening in there. 😉

**Comment by gardiol** [comment]
[home-assistant_solarman_2024-10-13T14-55-15.170Z.zip](https://github.com/user-attachments/files/17356057/home-assistant_solarman_2024-10-13T14-55-15.170Z.zip)

I changed the following code adding two IFs and relative logger at the beginning of the function:
```
   def do_validate(self, key, value, rule):
        if "min" in rule and (min := rule["min"]):
            _LOGGER.debug(f"do_validate {key}: {value} | min: {min}")
        else:
            _LOGGER.debug(f"do_validate {key}: {value} | no min in rule")
            
        if "max" in rule and (max := rule["max"]):
            _LOGGER.debug(f"do_validate {key}: {value} | max: {max}")
        else:
            _LOGGER.debug(f"do_validate {key}: {value} | no max in rule")

        if "min" in rule and (min := rule["min"]) and min > value:
            _LOGGER.debug(f"do_validate {key}: {value} < {min}")
            if "invalidate_all" in rule:
                raise ValueError(f"Invalidate complete dataset - {key}: {value} < {min}")
            return False

        if "max" in rule and (max := rule["max"]) and max < value:
            _LOGGER.debug(f"do_validate {key}: {value} > {max}")
            if "invalidate_all" in rule:
                raise ValueError(f"Invalidate complete dataset - {key}: {value} > {max}")
            return False
        return True
```

I am a C/C++ old fart, Python feels always... strange to meddle with :)

**Comment by gardiol** [comment]
I can confirm that setting 4294967 as max value on all the places where it was 0xFFFFFFFA effectively makes all those values "Unknown" (which is correct) plus fixes the "Total Losses" that are now calculated correctly!

Screenshot_20241013-171026_Home Assistant

**Comment by davidrapan** [comment]
> I am a C/C++ old fart, Python feels always... strange

Yeah I totally agree!

> it seems the max/mix should be changes to refer to the scaled/modified values instead of the original data...
Since the scale has changed, so should the max values as well

Yeeeeeeeey! I completele forgot about that!

max should be limited using:
```
range:
  max: 4294967289
```
instead of validation!

**Comment by davidrapan** [comment]
I'll fix it there promptly! Thanks for figuring that out! 🥂

**Comment by gardiol** [comment]
So range is applied before and validation after scaling?

I suggest to write a wiki page with all the little insights you provided me here on how to write those yamls...

I might get down on it if I have time, but cannot guarantee.

**Comment by davidrapan** [comment]
> So range is applied before and validation after scaling?

Exactly.

`range` property was added later as a way of be able to write `yaml`s in 1:1 with documentation and did not had deal with floats in validation.

It was the first time somewhere had to be set `max` so I completely forgot that validation had to be scaled too cause you don't care about it with `min`. 😉

> I suggest to write a wiki page with all the little insights you provided me here on how to write those yamls...

Yeah it's somehow getting bigger and bigger. 😆

**Comment by davidrapan** [comment]
[fix: chint_cps-scetl - ranges and validations](https://github.com/davidrapan/ha-solarman/commit/ecc1f705e0bea25363153ba4a423dc5e109ce759)

That should do! 😉

There can't be used range with custom sensors currently cause it would invalidate whole sensor.

**Pull request merged**
