### PR TITLE
Create pylontech_ForceHB_H_2-3.yaml

### PR DESCRIPTION
**Pull request by cryptocake**
Profile for adding the Pylontech ForceHB H2 or H3 Battery Pack in Home Assistant. This is helpful for the Dutch Zonneplan Nexus community [found here on Tweakers.net](https://gathering.tweakers.net/forum/list_messages/2230992/0).

### CODE REVIEW

**Comment by jeroenribbink** [comment]
I tried to Connect with the Zonneplan Nexus, but got an error instead. 

`Logger: homeassistant.config_entries
Bron: config_entries.py:586
Eerst voorgekomen: 4 augustus 2024 om 14:53:30 (4 gebeurtenissen)
Laatst gelogd: 06:36:38

Error setting up entry Inverter for solarman
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solarman/__init__.py", line 61, in async_setup_entry
    await inverter.load()
  File "/config/custom_components/solarman/api.py", line 143, in load
    self.parameter_definition = await yaml_open(self.lookup_path + self.lookup_file)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solarman/common.py", line 23, in yaml_open
    return yaml.safe_load(await f.read())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/usr/local/lib/python3.12/site-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
            ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yaml/scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "/usr/local/lib/python3.12/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 231, column 75:
     ... age-responsive" style="word-wrap: break-word;">
                                         ^
`

what could I possibly do to provide more info?

**Comment by cryptocake** [comment]
@jeroenribbink is that the full error?
Do you have the 20kWh battery?

**Comment by jeroenribbink** [comment]
> @jeroenribbink is that the full error? Do you have the 20kWh battery?

Yes it is, I made an screenshot to be sure you got the correct alignment of the text:
image

And indeed it is the 20kWh battery.
I can see all the info in the solarman smart app.

I tried connecting it with WIFI first and with ethernet the second try (and changed the IP accordingly).

**Comment by cryptocake** [comment]
> > @jeroenribbink is that the full error? Do you have the 20kWh battery?
> 
> Yes it is, I made an screenshot to be sure you got the correct alignment of the text: image
> 
> And indeed it is the 20kWh battery. I can see all the info in the solarman smart app.
> 
> I tried connecting it with WIFI first and with ethernet the second try (and changed the IP accordingly).

How did you copy the yaml profile? It could be that there is a bad indentation somewhere?
Can you try to overwrite the yaml file you have with: https://raw.githubusercontent.com/cryptocake/ha-solarman/cryptocake-patch-1/custom_components/solarman/inverter_definitions/pylontech_ForceHB_H_2-3.yaml

**Comment by davidrapan** [comment]
Does it mean it can't work with H1?

_Would love to avoid having specific type (capacity in this case) in file name if possible._

**Comment by cryptocake** [comment]
> Does it mean it can't work with H1?

I'm not sure, I got it from: https://gist.github.com/nagisa/435bdf783e4b13b8e810106b0852081e
It was made for the H2, and we have the H3 and that works too. Have no idea if it works for the H1.

> What does the "HB" in "ForceHB" mean? Could not find the device.

It is the devicename that the Pylontech BMS returns: `ForceHB_H3`, that's why I included the HB.

> _Would love to avoid having specific type (capacity in this case) in file name if possible._

Are you refering to the H2 / H3? I'm not even sure if that is a capacity, I thought it is just a model number? It is a modular battery system, each with a capacity of 5kWh.

> Edit: I'm not trying to be pedant here.. I'm just wondering should not be for example "Min Module Voltage" be "Module Min Voltage" and so on?

The entities in the profile reflect the entities that Solarmanpv.com and Soliscloud shows.

I hope this answers your questions. Please let me know what changes you would like me to make, I'm happy to do so.

**Comment by jeroenribbink** [comment]
> > > @jeroenribbink is that the full error? Do you have the 20kWh battery?
> > 
> > 
> > Yes it is, I made an screenshot to be sure you got the correct alignment of the text: image
> > And indeed it is the 20kWh battery. I can see all the info in the solarman smart app.
> > I tried connecting it with WIFI first and with ethernet the second try (and changed the IP accordingly).
> 
> How did you copy the yaml profile? It could be that there is a bad indentation somewhere? Can you try to overwrite the yaml file you have with: https://raw.githubusercontent.com/cryptocake/ha-solarman/cryptocake-patch-1/custom_components/solarman/inverter_definitions/pylontech_ForceHB_H_2-3.yaml

Oh snap, I used the download method of my browser to download the direct url of the tweakers.net post, but I've not checked is correctly, because it downloaded the GitHub page (slams the head). I should have used the Raw file of GitHub. which is the link you provided, thanks. Now the yaml is good and the device and sensors are load correctly.

The wifi connection is not working (I don't have the correct antenna, ordered one), but via Ethernet it is connecting fine.

**Comment by jeroenribbink** [comment]
Maybe this is a more common issue but after one connect and load attempt I got connect issues:
2024-08-05 12:33:28.011 ERROR (MainThread) [custom_components.solarman.api] Cannot open connection to 192.168.178.104. [ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.178.104', 8899)]
Traceback (most recent call last):
  File "/config/custom_components/solarman/api.py", line 42, in reconnect
    self.reader, self.writer = await asyncio.open_connection(self.address, self.port)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1122, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1104, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1007, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 641, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 681, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.178.104', 8899)

If I browse to the address http://192.168.178.104 it loads instant. Could this be something with the cloud? I thought all connections where made locally?

**Comment by jeroenribbink** [comment]
Enable debug logging and got this:
2024-08-05 12:40:45.512 DEBUG (MainThread) [custom_components.solarman.api] Querying attempts left: 1
2024-08-05 12:40:45.512 DEBUG (MainThread) [custom_components.solarman.api] Reader Task done: True, cancelled: False.
2024-08-05 12:40:45.513 DEBUG (MainThread) [custom_components.solarman.api] [3837206347] SENT: a5 17 00 10 45 1b 00 4b 1f b7 e4 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 03 10 00 00 0b 00 cd 7a 15
2024-08-05 12:40:45.513 WARNING (MainThread) [custom_components.solarman.api] Querying (4096 - 4106) failed. #330 [NoSocketAvailableError: Connection already closed]
2024-08-05 12:40:46.515 DEBUG (MainThread) [custom_components.solarman.api] Querying attempts left: 0, aborting.
2024-08-05 12:40:46.516 DEBUG (MainThread) [custom_components.solarman.api] Request failed. [Previous Status: Connected]
2024-08-05 12:40:46.516 INFO (MainThread) [custom_components.solarman.api] Disconnecting from 192.168.178.104:8899
2024-08-05 12:40:46.516 DEBUG (MainThread) [custom_components.solarman.coordinator] Finished fetching Pylontech Force H3 data in 5.027 seconds (success: True)

**Comment by jeroenribbink** [comment]
after reloading the configuration in the integration the log doesn't show errors with the connection anymore. I'll later try it again with debugging OFF.

**Comment by davidrapan** [comment]
There could be some disconnects or not fulfilled requests as solarman just simply sometimes refuses to respond.

**Comment by jeroenribbink** [comment]
> There could be some disconnects or not fulfilled requests as solarman just simply sometimes refuses to respond. The important part is if it reconnects back at the end.

It looks like is sending a new request at the interval (10sec) but I only see SENT calls no RESD calls anymore.
After reloading the data is fetched again for a brief moment and stops again.
Maybe I'll try to disable polling in the config of the integration and manually (automation) pol every minute.
Maybe that helps. let you know.

**Comment by cryptocake** [comment]
> Anyway would need you to get rid of the second and third underscore as underscore is used to separate manufacturer(brand) from the model. (Maybe pylontech_Force-H2|3 ?)

@davidrapan I'm not sure if having a pipe in the filename would be a good idea? 
What about: `pylontech_Force-H`? I already included both names H2 and H3 in the file's top comment.


Regarding the disconnects: 
I also experience them, but it always reconnects.
@jeroenribbink you could indeed experiment with the `update_interval: 10`, but somehow the solarman protocol that is being used in the Battery is unstable. When I tried to search for registers it sometimes just bugs out and I would find that even the webinterface became unresponsive.
I have only tried connecting over LAN, maybe it is more stable on WiFi? (that would be a first lol).

**Comment by davidrapan** [comment]
> I'm not sure if having a pipe in the filename would be a good idea?
lol, that's a typo. Sorry bout that but it should be protected from treating it any other way than just a string. But at the end one can never know, right? 😆

**Comment by cryptocake** [comment]
> > I'm not sure if having a pipe in the filename would be a good idea?
> 
> lol, that's a typo. Sorry bout that but it should be protected from treating it any other way than just a string. But at the end one can never know, right? 😆

Haha exactly, you'll never know ;-P
Thanks for the merge! 🥳 


> And I'm gonna be honest I'm somehow still baffled by the fact that even battery pack is using solarman. 😆

Lol yes I found that somewhat strange too, I first thought that I was connected to the inverter, but it turned out to be the battery. But hey, that's good enough for us 😆 

@jeroenribbink I switched from LAN to WiFi almost an hour ago... Had an antenna hidden in a box somewhere and used that on the antenna port. Let me tell you: haven't had 1 timeout ever since LOL, I'm baffled... 

One explanation could be: Because I configured WiFi and overwritten the DNS server entries in the webinterface, it does not phone-home to solarmanpv.com anymore. Maybe that function causes the protocol to run at its limits  (is ran every 5 minutes), and when ha-solarman polls at the same time, it maybe causes the protocol or network interface to overflow, causing it to temp crash the connection.
I'm not 100% sure... but it could be an explanation.

**Comment by jeroenribbink** [comment]
Wow, that’s crazy. Did you change de DNS from 10.10.100.254 to your home dns server?

**Comment by davidrapan** [comment]
> Maybe that function causes the protocol to run at its limits (is ran every 5 minutes), and when ha-solarman polls at the same time, it maybe causes the protocol or network interface to overflow, causing it to temp crash the connection.

You nailed it. That's exactly what is happening but it has more to do with the situation when your polling and sending to the solarman servers meets.

**Comment by jeroenribbink** [comment]
But if I just change the DNS and keep Ethernet would it also improve? Otherwise how can I remove the WiFi config just input invalid values?

**Comment by davidrapan** [comment]
I'm not really familiar with ethernet version so not sure...

**Comment by jeroenribbink** [comment]
> I'm not really familiar with ethernet version so not sure...

Okay, no problem. 
Did you change anything to the DNS settings? If so, did you change it to your local dns or something else?

**Comment by davidrapan** [comment]
I have configured DNS hijack in the router so all 53 DNS requests are handled by my router no matter the IP configured so no I did not change that.

**Comment by jeroenribbink** [comment]
Oh that is not something I am familiar with. 
And I am not sure if my router is capable of hijacking specific traffic. 

But in the end, the goal is to block the calls to the cloud, right?

**Comment by davidrapan** [comment]
If you want to block them remove values for Server A in: http://192.168.178.104/config_hide.html

**Pull request merged**
