### PR TITLE
Update deye_2mppt.yaml

### PR DESCRIPTION
**Pull request by CrazyUs3r**
scale to set 100% not 10%

### CODE REVIEW

**Comment by davidrapan** [comment]
Can you show me the value it shows to you? Just to be sure... _Maybe there is difference to 4MPPT though...._

**Comment by CrazyUs3r** [comment]
10.2 with Scale 0.1 and 102 with scale 1
Screenshot_20240814_060350_Home Assistant
Screenshot_20240814_060353_Home Assistant

**Comment by CrazyUs3r** [comment]
Yes with the yaml i can set 0 to 120% its work good

**Comment by davidrapan** [comment]
Another question, where did you got this list?
```
          - key: 0x0000
            value: "OK"
          - key: 0x1
            value: "DC OverVoltage"
          - key: 0x2
            value: "DC Bus OverVoltage"
          - key: 0x4
            value: "DC Bus Uneven Voltage"
          - key: 0x8
            value: "DC Bus UnderVoltage"
          - key: 0x10
            value: "DC Bus2 Uneven Voltage"
          - key: 0x20
            value: "DC A path OverCurrent"
          - key: 0x40
            value: "DC B path OverCurrent"
          - key: 0x80
            value: "DC Input Disturbance"
          - key: 0x100
            value: "Grid OverCurrent"
          - key: 0x200
            value: "IGBT OverCurrent"
          - key: 0x400
            value: "Grid Disturbance 2"
          - key: 0x800
            value: "Arc Self-Test Protection"
          - key: 0x1000
            value: "Arc Fault Reservation"
          - key: 0x2000
            value: "Grid Current Sample Abnormality"
```

Cause some values are conflicting with the FXX table from the https://github.com/user-attachments/files/16597960/Deye.Modbus.protocol.V118.pdf

**Comment by CrazyUs3r** [comment]
I have the same doc but i ask deye for a New doc

**Comment by davidrapan** [comment]
Can you share?

**Comment by CrazyUs3r** [comment]
sure if I get something new I will share it. I also sent a question to deye about the error

**Comment by davidrapan** [comment]
Great! Let me know if they reach out to you.

For now I don't know what to do though as I started with enhancing of the "Device Fault" messaging (you can see in the sg04lp3 profile) and it seems so that it should be similiar also for the 2mppt and 4mppt but I'm not sure what to do with those conflicting values...

**Comment by CrazyUs3r** [comment]
Dear Sir/Madam,

We have received your message. We apologize, but the Modbus protocol of our micro-inverter products is not open to the public, so we are unable to send the documentation to you. If you encounter any further issues, please feel free to contact us. We wish you all the best.

Sincerely,

Heran Zhang
deye technical support

**Comment by davidrapan** [comment]
Yes yes I thought so!

**Comment by CrazyUs3r** [comment]
Dear Sir/Madam,

We have received your message. Please send us the serial numbers of your inverter and Logger, along with the blinking status of the micro inverter and the relay (if you are using G3 series or MG3 series models). If the device is malfunctioning, we can remotely check the device's status (if you have previously configured the network) to help diagnose the issue and provide a solution.

Additionally, the F01-F64 error codes only appear on the display of Hybrid Inverters and Grid-connected PV Inverters. Therefore, if you have purchased a micro inverter, there shouldn't be any explanations regarding these error codes. If you encounter any further issues, please feel free to contact us. We wish you all the best.

Sincerely,
Heran Zhang
deye technical support

**Pull request merged**
