### PR TITLE
Update deye_2mppt.yaml

### PR DESCRIPTION
**Pull request by CrazyUs3r**

### CODE REVIEW

**Comment by davidrapan** [comment]
Hi @CrazyUs3r!

Thanks for your PR. I have just few questinos:
You sure that definition like this works though?:
```
- key: F07
  value: "F07 - DC/DC_Softsart_Fault"
```

And when comes to naming I don't the suffix 'Enable' in the 'Soft Start Enable' is needed as it's obvious from entity type and it's somewhat redundant.

**Comment by CrazyUs3r** [comment]
hey
I'll go through all the alarm codes soon and then write down all the values. F07 is in the Modbus pdf from deye

**Comment by davidrapan** [comment]
Yeah I was rather talking about the "translation of read registry value" to that particular key...

**Comment by CrazyUs3r** [comment]
The rest of the F07 is probably never used because, for example, the 128 comes with a weak DC voltage.

You are also right about the double soft start enable if it is double in the yaml, then in the sensor area only the value is displayed but no text

**Comment by davidrapan** [comment]
And please try to be little more descriptive in the commit messages. Prefix it with fix: or feat: depends on circumstances and what did you changed in few words.

Thanks for you PR!

**Pull request merged**
