### PR TITLE
Afore Aton T6 added

### PR DESCRIPTION
**Pull request by pmitrus**

### CODE REVIEW

**Comment by davidrapan** [comment]
Hi @pmitrus, profile with these registers already exists: `afore_hybrid.yaml`

**Comment by pmitrus** [comment]
I partially agree but I have BNT004KTL then I tried BNTxxxKTL-2mppt.yaml because it matches by name - but this won't work. Important is if HW verion is T4 or T6 then I added this profile clearly for Afore Aton users with T6 hardware version. Which are not interested with all battery statuses which Aton doesnt have while Hybrid have.

**Comment by pmitrus** [comment]
Or just rename existing profiles with info that hybrid is also working with BNT***KTL with serial numbers from T6xxx (named as ATON)

**Comment by davidrapan** [comment]
Okay so if you want profile stripped of some not relevant entities for your particular device that's okay but make sure that entity names are the same as in the other profile.

If "T6" does not resemble model of the device remove it from the name and simply clarify what's going in the file in comments.

**Comment by pmitrus** [comment]
I'll clean up and make description to all Afore ones. But need to test tomorrow when inverter will be online.

**Pull request closed without merging**
